name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build extension
      run: npm run compile
      
    - name: Package extension
      run: npm run package
      
    - name: Install vsce
      run: npm install -g @vscode/vsce
      
    - name: Package VSIX
      run: vsce package
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release
          
          Please see [CHANGELOG.md](CHANGELOG.md) for detailed information about this release.
          
          ## Installation
          
          Download the `.vsix` file below and install it in VS Code:
          1. Open VS Code
          2. Go to Extensions view (Ctrl+Shift+X)
          3. Click "..." menu → "Install from VSIX..."
          4. Select the downloaded file
          
          ## What's New
          
          - Check the changelog for detailed feature list
          - All tests passing
          - Ready for production use
        draft: false
        prerelease: false
        
    - name: Upload VSIX Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./l1x-elavonx-migrator-${{ steps.get_version.outputs.VERSION }}.vsix
        asset_name: l1x-elavonx-migrator-${{ steps.get_version.outputs.VERSION }}.vsix
        asset_content_type: application/zip